### ISSUE TITLE
[Feature Suggestion] The ability to upload custom rings

### ISSUE THREAD

**Issue by KLSteinwand** [ChasarooniZ/PF2e-Reactive-Token-Ring#12]
As updating Foundry replaces it's default token folder, there's no way to assign which custom rings to use without the assistance of a module. Being able to choose a file for the rings would be helpful as Core does seem to allow for the selection of a different ring, there's no option to upload or select a file.

**Comment by ChasarooniZ** [comment]
Going to put this in longterm hiatus as it's more complicated than I want to tackle now

**Comment by KLSteinwand** [comment]
No worries, don't overdo yourself!

**Comment by Mystler** [comment]
This feature would come with a bunch of complications since token rings are currently set up to be made by people that know what they are doing. They require more complicated json definition files and spritesheets with multiple instances and sizes of the token making it nowhere near as simple as uploading a single ring image. Even if a user uploaded a proper spritesheet the scaling may be unexpected and out of what if the expectation foundry conventions are not met.

So, I think while this feature is not impossible, it also seems out of scope for this module. Some kind of dynamic token ring editor that tries to somehow guide users through the process of creating custom versions would seem more fitting for a separate module (if anyone wants to bother implementing it), or maybe a module like Tokenizer that already centers around creating tokens and offering graphical editors.

**Comment by ChasarooniZ** [comment]
yeah for sure (i've considered it as a separate module , but as said it requires a lot of work)

If i were to do one it'd be more barebones and have pretty strict requirements for upload but it's not undoable per sae

I also think there may be value in a "Community Token Rings" type module, but my progress on that has been murky so far
